name: youtube_clone
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.3.0
  youtube_explode_dart: ^2.0.2
  shared_preferences: ^2.2.2
  youtube_player_flutter: ^8.1.2
  share_plus: ^7.2.1
  rename: ^3.0.1

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/icon.jpeg"
  min_sdk_android: 21

module:
  androidX: true 

flutter:
  uses-material-design: true
